name: todo_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  crypt: ^4.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.4
  intl: ^0.18.1
  progress_state_button: ^1.0.4
  rounded_loading_button: ^2.1.0
  supabase_flutter: ^2.3.4
  table_calendar: ^3.0.9
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
flutter_intl:
  enabled: true
